### ISSUE TITLE
Развитие либы

### ISSUE THREAD

**Issue by AlexeySpiridonov** [Emericanec/goAmoCrm#1]
Какое то развитие планируется?

**Comment by Emericanec** [comment]
Сори немного подзабил. Да я думаю развитие будет.

**Comment by AlexeySpiridonov** [comment]
У меня есть предложение сделать вот так:

amo, err := goAMO.New(url, email, token)

clients, err := amo.Clients.List(params)

for _, c :=range clients {
   c.Name = "Васек"
   amo.Clients.Save(c)
}

err := amo.Clients.New( goAmo.Client{Tel:"12343424"} )

 могу каркас накидать, но нужна будет помощь с доработкой до поддержки
всего апи

2017-05-30 23:05 GMT+07:00 Andrey Svetlichniy <notifications@github.com>:

**Comment by Emericanec** [comment]
Да давай. Можешь кидать пул реквест
